[build]
  publish = "public"
  command = "npm run build"
  node_version = "18"

[context.master]
  NODE_ENV = "production"

[context.deploy]
  NODE_ENV = "development"

[context.branch-deploy]
  NODE_ENV = "development"
